name: Tests

env:
  # prisma setip
  PRISMA_CLI_BINARY_TARGETS: "debian-openssl-3.0.x"
  DATABASE_URL: "file:./database/data.db"
  # api setup
  WAR_ID: "801"
  RATE_LIMIT: "200"
  API_URL: "https://api.live.prod.thehelldiversgame.com/api"
  # stratagem setup
  STRATAGEM_IMAGE_URL: "https://vxspqnuarwhjjbxzgauv.supabase.co/storage/v1/object/public/stratagems"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bunx prisma generate
      - run: bunx prisma migrate dev
      - run: bun generate
      - run: bun test
