name: Tests

env:
  # prisma setip
  DATABASE_URL: "file:./database/data.db"
  # api setup
  RATE_LIMIT: "200"
  HISTORY_API_URL: "https://helldivers-b.omnedia.com/api"
  API_URL: "https://api.live.prod.thehelldiversgame.com/api"
  # stratagem setup
  STORAGE_URL: "https://vxspqnuarwhjjbxzgauv.supabase.co/storage/v1/object/public"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bunx prisma generate
      - run: bunx prisma migrate deploy
      - run: bun generate
      - run: bun test
